services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    environment:
      NG_ALLOWED_HOSTS: $DOMAIN,*.$DOMAIN
    restart: unless-stopped
