services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4003:4003"
      - "4004:4004"
      - "4005:4005"
    restart: unless-stopped
