import { MotionLayer, MotionTransition } from '../schema/motion-document';

export interface MotionPreset {
  id: string;
  name: string;
  description: string;
  category:
    | 'text'
    | 'shape'
    | 'scene'
    | 'lower-third'
    | 'metric'
    | 'background'
    | 'quote'
    | 'product'
    | 'cta'
    | 'chart';
  layers: MotionLayer[];
  scene?: {
    duration?: number;
    transitionIn?: MotionTransition;
    transitionOut?: MotionTransition;
  };
}

export const MOTION_PRESETS: MotionPreset[] = [
  {
    id: 'text-heading',
    name: 'Heading',
    description: 'Large editorial text layer.',
    category: 'text',
    layers: [
      {
        id: 'preset-heading',
        type: 'text',
        name: 'Heading',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 160, y: 152, width: 860, height: 130 },
        style: {
          color: '#ffffff',
          fontSize: 88,
          fontWeight: 800,
          lineHeight: 1.35,
        },
        props: { text: 'Heading' },
      },
    ],
  },
  {
    id: 'text-subtitle',
    name: 'Subtitle',
    description: 'Compact supporting copy.',
    category: 'text',
    layers: [
      {
        id: 'preset-subtitle',
        type: 'text',
        name: 'Subtitle',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 164, y: 300, width: 760, height: 120 },
        style: {
          color: '#dbeafe',
          fontSize: 57,
          fontWeight: 500,
          lineHeight: 1.16,
        },
        props: { text: 'Subtitle text' },
      },
    ],
  },
  {
    id: 'text-caption',
    name: 'Caption',
    description: 'Readable subtitle band for narrated clips.',
    category: 'text',
    layers: [
      {
        id: 'preset-caption',
        type: 'caption',
        name: 'Caption',
        start: 0,
        duration: 3200,
        zIndex: 6,
        layout: { x: 330, y: 818, width: 1260, height: 198 },
        style: {
          color: '#ffffff',
          background: '#020617',
          borderRadius: 30,
          fontSize: 69,
          fontWeight: 600,
          lineHeight: 1.18,
        },
        props: { text: 'Caption text' },
      },
    ],
  },
  {
    id: 'text-kicker',
    name: 'Kicker',
    description: 'Small uppercase label.',
    category: 'text',
    layers: [
      {
        id: 'preset-kicker',
        type: 'text',
        name: 'Kicker',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 160, y: 110, width: 460, height: 44 },
        style: {
          color: '#93c5fd',
          fontSize: 28,
          fontWeight: 700,
          lineHeight: 1,
          letterSpacing: 2,
        },
        props: { text: 'SECTION' },
      },
    ],
  },
  {
    id: 'text-number',
    name: 'Number',
    description: 'Large metric number.',
    category: 'text',
    layers: [
      {
        id: 'preset-number',
        type: 'text',
        name: 'Number',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 152, y: 178, width: 560, height: 160 },
        style: {
          color: '#ffffff',
          fontSize: 118,
          fontWeight: 800,
          lineHeight: 0.96,
        },
        props: { text: '+42%' },
      },
    ],
  },
  {
    id: 'shape-card',
    name: 'Card',
    description: 'Rounded surface block.',
    category: 'shape',
    layers: [
      {
        id: 'preset-card',
        type: 'shape',
        name: 'Card',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 120, y: 128, width: 780, height: 420 },
        style: { background: '#ffffff', borderRadius: 36 },
        props: { kind: 'rectangle' },
      },
    ],
  },
  {
    id: 'shape-pill',
    name: 'Pill',
    description: 'Rounded label shape.',
    category: 'shape',
    layers: [
      {
        id: 'preset-pill',
        type: 'shape',
        name: 'Pill',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 150, y: 150, width: 340, height: 86 },
        style: { background: '#2563eb', borderRadius: 999 },
        props: { kind: 'rectangle' },
      },
    ],
  },
  {
    id: 'shape-circle',
    name: 'Circle',
    description: 'Circular accent element.',
    category: 'shape',
    layers: [
      {
        id: 'preset-circle',
        type: 'shape',
        name: 'Circle',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 240, y: 190, width: 260, height: 260 },
        style: { background: '#22d3ee', borderRadius: 999 },
        props: { kind: 'ellipse' },
      },
    ],
  },
  {
    id: 'shape-line',
    name: 'Line',
    description: 'Thin divider or underline.',
    category: 'shape',
    layers: [
      {
        id: 'preset-line',
        type: 'shape',
        name: 'Line',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 160, y: 380, width: 520, height: 12 },
        style: { background: '#60a5fa', borderRadius: 0 },
        props: { kind: 'line' },
      },
    ],
  },
  {
    id: 'shape-blob-path',
    name: 'Blob path',
    description: 'Editable SVG path accent.',
    category: 'shape',
    layers: [
      {
        id: 'preset-blob-path',
        type: 'path',
        name: 'Blob path',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 900, y: 160, width: 420, height: 300, rotation: -8 },
        style: { fill: '#38bdf8', stroke: '#ffffff', strokeWidth: 0 },
        props: {
          d: 'M 8 50 C 20 12, 64 2, 84 28 C 110 62, 78 94, 42 91 C 10 88, -5 68, 8 50 Z',
          viewBox: '0 0 100 100',
        },
      },
    ],
  },
  {
    id: 'chart-waveform',
    name: 'Waveform',
    description: 'Animated audio waveform strip.',
    category: 'chart',
    layers: [
      {
        id: 'preset-waveform',
        type: 'waveform',
        name: 'Waveform',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 220, y: 720, width: 980, height: 140 },
        style: { color: '#38bdf8' },
        props: {
          samples: [0.18, 0.42, 0.68, 0.36, 0.82, 0.48, 0.92, 0.34, 0.64, 0.74, 0.28, 0.56],
        },
      },
    ],
  },
  {
    id: 'title-reveal',
    name: 'Intro title',
    description: 'Large title with an animated accent bar.',
    category: 'scene',
    scene: {
      duration: 3800,
      transitionIn: { type: 'fade', duration: 420, easing: 'easeOutCubic' },
      transitionOut: {
        type: 'wipe',
        duration: 520,
        easing: 'easeInOutCubic',
        props: { direction: 'right' },
      },
    },
    layers: [
      {
        id: 'preset-title',
        type: 'text',
        name: 'Title',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 140, y: 180, width: 980, height: 180 },
        style: {
          color: '#ffffff',
          fontSize: 86,
          fontWeight: 700,
          lineHeight: 1.05,
        },
        props: { text: 'New scene' },
        transitions: {
          in: {
            type: 'slide',
            duration: 600,
            easing: 'easeOutCubic',
            props: { direction: 'left', distance: 140 },
          },
          out: {
            type: 'fade',
            duration: 500,
            easing: 'easeInOutCubic',
          },
        },
        animations: [
          {
            property: 'opacity',
            keyframes: [
              { time: 0, value: 0 },
              { time: 500, value: 1, easing: 'easeOutCubic' },
            ],
          },
          {
            property: 'y',
            keyframes: [
              { time: 0, value: 218 },
              { time: 500, value: 180, easing: 'easeOutCubic' },
            ],
          },
        ],
      },
      {
        id: 'preset-accent',
        type: 'shape',
        name: 'Accent',
        start: 120,
        duration: 3200,
        zIndex: 1,
        layout: { x: 140, y: 380, width: 520, height: 16 },
        style: { background: '#22d3ee', borderRadius: 999 },
        props: { kind: 'rectangle' },
        transitions: {
          in: {
            type: 'wipe',
            duration: 650,
            easing: 'easeOutCubic',
            props: { direction: 'left' },
          },
        },
        animations: [
          {
            property: 'width',
            keyframes: [
              { time: 0, value: 0 },
              { time: 520, value: 520, easing: 'easeOutCubic' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'scene-metric-slide',
    name: 'Metric slide',
    description: 'Data point with label and supporting panel.',
    category: 'scene',
    scene: {
      duration: 4200,
      transitionIn: { type: 'fade', duration: 360, easing: 'easeOutCubic' },
      transitionOut: { type: 'slide', duration: 520, easing: 'easeInOutCubic', props: { direction: 'left', distance: 90 } },
    },
    layers: [
      {
        id: 'preset-metric-slide-bg',
        type: 'shape',
        name: 'Metric background',
        start: 0,
        duration: 4200,
        zIndex: 1,
        layout: { x: 120, y: 120, width: 900, height: 560 },
        style: { background: '#f8fafc', borderRadius: 34 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-metric-slide-value',
        type: 'text',
        name: 'Metric value',
        start: 160,
        duration: 3900,
        zIndex: 2,
        layout: { x: 180, y: 220, width: 560, height: 150 },
        style: { color: '#0f172a', fontSize: 116, fontWeight: 850, lineHeight: 0.95 },
        props: { text: '+42%' },
        transitions: {
          in: {
            type: 'scale',
            duration: 520,
            easing: 'easeOutBack',
          },
        },
      },
      {
        id: 'preset-metric-slide-label',
        type: 'text',
        name: 'Metric label',
        start: 260,
        duration: 3800,
        zIndex: 2,
        layout: { x: 190, y: 395, width: 560, height: 76 },
        style: { color: '#475569', fontSize: 36, fontWeight: 500, lineHeight: 1.12 },
        props: { text: 'Pipeline growth this quarter' },
      },
      {
        id: 'preset-metric-slide-accent',
        type: 'shape',
        name: 'Metric accent',
        start: 300,
        duration: 3600,
        zIndex: 2,
        layout: { x: 188, y: 505, width: 440, height: 14 },
        style: { background: '#2563eb', borderRadius: 999 },
        props: { kind: 'rectangle' },
        transitions: {
          in: {
            type: 'wipe',
            duration: 560,
            easing: 'easeOutCubic',
            props: { direction: 'left' },
          },
        },
      },
    ],
  },
  {
    id: 'scene-testimonial',
    name: 'Testimonial',
    description: 'Quote layout with author caption.',
    category: 'scene',
    scene: {
      duration: 5000,
      transitionIn: { type: 'slide', duration: 520, easing: 'easeOutCubic', props: { direction: 'up', distance: 80 } },
      transitionOut: { type: 'fade', duration: 420, easing: 'easeInOutCubic' },
    },
    layers: [
      {
        id: 'preset-testimonial-panel',
        type: 'shape',
        name: 'Quote panel',
        start: 0,
        duration: 5000,
        zIndex: 1,
        layout: { x: 132, y: 138, width: 1080, height: 560 },
        style: { background: '#ffffff', borderRadius: 38 },
        props: { kind: 'rectangle' },
        transitions: {
          in: { type: 'fade', duration: 420, easing: 'easeOutCubic' },
          out: { type: 'fade', duration: 360, easing: 'easeInOutCubic' },
        },
      },
      {
        id: 'preset-testimonial-quote',
        type: 'text',
        name: 'Quote',
        start: 220,
        duration: 4560,
        zIndex: 2,
        layout: { x: 210, y: 230, width: 920, height: 260 },
        style: { color: '#111827', fontSize: 58, fontWeight: 700, lineHeight: 1.08 },
        props: { text: '“This gave our team a repeatable motion system in days.”' },
        transitions: {
          in: {
            type: 'slide',
            duration: 560,
            easing: 'easeOutCubic',
            props: { direction: 'up', distance: 72 },
          },
        },
      },
      {
        id: 'preset-testimonial-author',
        type: 'text',
        name: 'Author',
        start: 520,
        duration: 4100,
        zIndex: 2,
        layout: { x: 214, y: 545, width: 680, height: 58 },
        style: { color: '#475569', fontSize: 30, fontWeight: 600, lineHeight: 1 },
        props: { text: 'Maya Chen, Creative Ops' },
      },
    ],
  },
  {
    id: 'scene-product-shot',
    name: 'Product shot',
    description: 'Product frame with headline and callout.',
    category: 'scene',
    scene: {
      duration: 4600,
      transitionIn: { type: 'scale', duration: 520, easing: 'easeOutBack' },
      transitionOut: { type: 'wipe', duration: 520, easing: 'easeInOutCubic', props: { direction: 'right' } },
    },
    layers: [
      {
        id: 'preset-product-bg',
        type: 'shape',
        name: 'Product backdrop',
        start: 0,
        duration: 4600,
        zIndex: 0,
        layout: { x: 0, y: 0, width: 1920, height: 1080 },
        style: { background: '#eff6ff', borderRadius: 0 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-product-card',
        type: 'image',
        name: 'Product media',
        start: 120,
        duration: 4200,
        zIndex: 1,
        layout: { x: 770, y: 160, width: 760, height: 560 },
        style: { background: '#ffffff', borderRadius: 44, objectFit: 'cover' },
        props: { placeholder: true },
        transitions: {
          in: {
            type: 'scale',
            duration: 560,
            easing: 'easeOutBack',
          },
        },
      },
      {
        id: 'preset-product-title',
        type: 'text',
        name: 'Product headline',
        start: 220,
        duration: 4040,
        zIndex: 2,
        layout: { x: 210, y: 240, width: 520, height: 170 },
        style: { color: '#1e3a8a', fontSize: 72, fontWeight: 800, lineHeight: 1.02 },
        props: { text: 'Launch-ready motion' },
      },
      {
        id: 'preset-product-caption',
        type: 'text',
        name: 'Product caption',
        start: 420,
        duration: 3800,
        zIndex: 2,
        layout: { x: 214, y: 440, width: 510, height: 116 },
        style: { color: '#334155', fontSize: 34, fontWeight: 500, lineHeight: 1.18 },
        props: { text: 'Build branded scenes from reusable blocks.' },
      },
    ],
  },
  {
    id: 'scene-outro',
    name: 'Outro',
    description: 'Closing title and simple call to action.',
    category: 'scene',
    scene: {
      duration: 3600,
      transitionIn: { type: 'fade', duration: 460, easing: 'easeOutCubic' },
      transitionOut: { type: 'fade', duration: 620, easing: 'easeInOutCubic' },
    },
    layers: [
      {
        id: 'preset-outro-bg',
        type: 'shape',
        name: 'Outro background',
        start: 0,
        duration: 3600,
        zIndex: 0,
        layout: { x: 0, y: 0, width: 1920, height: 1080 },
        style: { background: '#111827', borderRadius: 0 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-outro-title',
        type: 'text',
        name: 'Outro title',
        start: 180,
        duration: 3100,
        zIndex: 2,
        layout: { x: 220, y: 280, width: 980, height: 140 },
        style: { color: '#ffffff', fontSize: 84, fontWeight: 800, lineHeight: 1.02 },
        props: { text: 'Thanks for watching' },
        transitions: {
          in: { type: 'fade', duration: 520, easing: 'easeOutCubic' },
        },
      },
      {
        id: 'preset-outro-cta',
        type: 'text',
        name: 'Outro CTA',
        start: 420,
        duration: 2800,
        zIndex: 2,
        layout: { x: 224, y: 445, width: 760, height: 64 },
        style: { color: '#93c5fd', fontSize: 36, fontWeight: 600, lineHeight: 1 },
        props: { text: 'Create the next scene.' },
      },
    ],
  },
  {
    id: 'lower-third-name',
    name: 'Name lower third',
    description: 'Name and role caption bar.',
    category: 'lower-third',
    layers: [
      {
        id: 'preset-lt-bg',
        type: 'shape',
        name: 'Lower third panel',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 120, y: 760, width: 860, height: 150 },
        style: { background: '#ffffff', borderRadius: 28 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-lt-name',
        type: 'text',
        name: 'Name',
        start: 0,
        duration: 3600,
        zIndex: 3,
        layout: { x: 170, y: 792, width: 620, height: 58 },
        style: { color: '#0f172a', fontSize: 44, fontWeight: 800, lineHeight: 1 },
        props: { text: 'Alex Morgan' },
      },
      {
        id: 'preset-lt-role',
        type: 'text',
        name: 'Role',
        start: 0,
        duration: 3600,
        zIndex: 3,
        layout: { x: 172, y: 852, width: 640, height: 38 },
        style: { color: '#475569', fontSize: 26, fontWeight: 500, lineHeight: 1 },
        props: { text: 'VP Revenue Operations' },
      },
    ],
  },
  {
    id: 'metric-card',
    name: 'Metric card',
    description: 'Card with metric and label.',
    category: 'metric',
    layers: [
      {
        id: 'preset-metric-bg',
        type: 'shape',
        name: 'Metric panel',
        start: 0,
        duration: 3600,
        zIndex: 1,
        layout: { x: 132, y: 150, width: 620, height: 360 },
        style: { background: '#1e293b', borderRadius: 34 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-metric-value',
        type: 'text',
        name: 'Metric value',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 188, y: 236, width: 440, height: 128 },
        style: { color: '#ffffff', fontSize: 104, fontWeight: 800, lineHeight: 0.95 },
        props: { text: '+42%' },
      },
      {
        id: 'preset-metric-label',
        type: 'text',
        name: 'Metric label',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 194, y: 380, width: 420, height: 42 },
        style: { color: '#bfdbfe', fontSize: 30, fontWeight: 500, lineHeight: 1 },
        props: { text: 'Pipeline growth' },
      },
    ],
  },
  {
    id: 'background-blueprint',
    name: 'Blueprint background',
    description: 'Full frame technical backdrop.',
    category: 'background',
    layers: [
      {
        id: 'preset-bg-blue',
        type: 'shape',
        name: 'Blueprint background',
        start: 0,
        duration: 5000,
        zIndex: -10,
        layout: { x: 0, y: 0, width: 1920, height: 1080 },
        style: { background: '#0f172a', borderRadius: 0 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-bg-panel',
        type: 'shape',
        name: 'Soft panel',
        start: 0,
        duration: 5000,
        zIndex: -9,
        layout: { x: 1180, y: 120, width: 520, height: 780 },
        style: { background: '#1d4ed8', borderRadius: 46 },
        props: { kind: 'rectangle' },
      },
    ],
  },
  {
    id: 'quote-pull',
    name: 'Pull quote',
    description: 'Editorial quote block with attribution.',
    category: 'quote',
    layers: [
      {
        id: 'preset-quote-mark',
        type: 'text',
        name: 'Quote mark',
        start: 0,
        duration: 4200,
        zIndex: 1,
        layout: { x: 130, y: 118, width: 130, height: 120 },
        style: { color: '#60a5fa', fontSize: 132, fontWeight: 800, lineHeight: 0.9 },
        props: { text: '"' },
      },
      {
        id: 'preset-quote-text',
        type: 'text',
        name: 'Quote',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 220, y: 154, width: 980, height: 180 },
        style: { color: '#ffffff', fontSize: 56, fontWeight: 650, lineHeight: 1.08 },
        props: { text: 'The fastest way to explain the work is to show it moving.' },
      },
      {
        id: 'preset-quote-credit',
        type: 'text',
        name: 'Attribution',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 224, y: 374, width: 520, height: 44 },
        style: { color: '#bfdbfe', fontSize: 28, fontWeight: 500, lineHeight: 1 },
        props: { text: 'Design lead' },
      },
    ],
  },
  {
    id: 'product-card',
    name: 'Product card',
    description: 'Image placeholder, title, copy, and price.',
    category: 'product',
    layers: [
      {
        id: 'preset-product-surface',
        type: 'shape',
        name: 'Product surface',
        start: 0,
        duration: 4200,
        zIndex: 1,
        layout: { x: 120, y: 110, width: 660, height: 500 },
        style: { background: '#ffffff', borderRadius: 34 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-product-media',
        type: 'shape',
        name: 'Product media',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 160, y: 150, width: 260, height: 260 },
        style: { background: '#dbeafe', borderRadius: 26 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-product-title',
        type: 'text',
        name: 'Product title',
        start: 0,
        duration: 4200,
        zIndex: 3,
        layout: { x: 450, y: 166, width: 260, height: 92 },
        style: { color: '#0f172a', fontSize: 38, fontWeight: 750, lineHeight: 1.08 },
        props: { text: 'Launch Pack' },
      },
      {
        id: 'preset-product-copy',
        type: 'text',
        name: 'Product copy',
        start: 0,
        duration: 4200,
        zIndex: 3,
        layout: { x: 452, y: 280, width: 250, height: 88 },
        style: { color: '#475569', fontSize: 22, fontWeight: 400, lineHeight: 1.24 },
        props: { text: 'Everything needed to ship motion-led updates.' },
      },
      {
        id: 'preset-product-price',
        type: 'text',
        name: 'Product price',
        start: 0,
        duration: 4200,
        zIndex: 3,
        layout: { x: 452, y: 430, width: 220, height: 54 },
        style: { color: '#2563eb', fontSize: 42, fontWeight: 800, lineHeight: 1 },
        props: { text: '$49' },
      },
    ],
  },
  {
    id: 'chart-bars',
    name: 'Bar chart',
    description: 'Three-column comparison chart.',
    category: 'chart',
    layers: [
      {
        id: 'preset-chart-title',
        type: 'text',
        name: 'Chart title',
        start: 0,
        duration: 4200,
        zIndex: 3,
        layout: { x: 140, y: 110, width: 720, height: 72 },
        style: { color: '#ffffff', fontSize: 48, fontWeight: 750, lineHeight: 1 },
        props: { text: 'Revenue by channel' },
      },
      ...[0, 1, 2].map((index) => ({
        id: `preset-chart-bar-${index}`,
        type: 'shape' as const,
        name: `Bar ${index + 1}`,
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: {
          x: 170 + index * 190,
          y: 490 - index * 70,
          width: 110,
          height: 180 + index * 70,
        },
        style: { background: ['#60a5fa', '#34d399', '#fbbf24'][index], borderRadius: 20 },
        props: { kind: 'rectangle' },
      })),
    ],
  },
  {
    id: 'comparison-split',
    name: 'Comparison',
    description: 'Before and after comparison layout.',
    category: 'chart',
    layers: [
      {
        id: 'preset-before-panel',
        type: 'shape',
        name: 'Before panel',
        start: 0,
        duration: 4200,
        zIndex: 1,
        layout: { x: 112, y: 150, width: 500, height: 390 },
        style: { background: '#1e293b', borderRadius: 32 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-after-panel',
        type: 'shape',
        name: 'After panel',
        start: 0,
        duration: 4200,
        zIndex: 1,
        layout: { x: 668, y: 150, width: 500, height: 390 },
        style: { background: '#2563eb', borderRadius: 32 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-before-label',
        type: 'text',
        name: 'Before',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 160, y: 205, width: 250, height: 62 },
        style: { color: '#cbd5e1', fontSize: 42, fontWeight: 700, lineHeight: 1 },
        props: { text: 'Before' },
      },
      {
        id: 'preset-after-label',
        type: 'text',
        name: 'After',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 716, y: 205, width: 250, height: 62 },
        style: { color: '#ffffff', fontSize: 42, fontWeight: 700, lineHeight: 1 },
        props: { text: 'After' },
      },
    ],
  },
  {
    id: 'cta-end-card',
    name: 'CTA card',
    description: 'Closing card with headline and action.',
    category: 'cta',
    layers: [
      {
        id: 'preset-cta-surface',
        type: 'shape',
        name: 'CTA surface',
        start: 0,
        duration: 4200,
        zIndex: 1,
        layout: { x: 170, y: 170, width: 940, height: 360 },
        style: { background: '#0f172a', borderRadius: 44 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-cta-title',
        type: 'text',
        name: 'CTA title',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 250, y: 238, width: 780, height: 90 },
        style: { color: '#ffffff', fontSize: 64, fontWeight: 800, lineHeight: 1 },
        props: { text: 'Ready to build the next deck?' },
      },
      {
        id: 'preset-cta-button',
        type: 'shape',
        name: 'CTA button',
        start: 0,
        duration: 4200,
        zIndex: 2,
        layout: { x: 250, y: 378, width: 260, height: 72 },
        style: { background: '#2563eb', borderRadius: 999 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-cta-button-text',
        type: 'text',
        name: 'CTA text',
        start: 0,
        duration: 4200,
        zIndex: 3,
        layout: { x: 296, y: 398, width: 180, height: 36 },
        style: { color: '#ffffff', fontSize: 28, fontWeight: 700, lineHeight: 1 },
        props: { text: 'Start now' },
      },
    ],
  },
];
