import { MotionLayer } from '../schema/motion-document';

export interface MotionPreset {
  id: string;
  name: string;
  description: string;
  category: 'text' | 'shape' | 'scene' | 'lower-third' | 'metric' | 'background';
  layers: MotionLayer[];
}

export const MOTION_PRESETS: MotionPreset[] = [
  {
    id: 'text-heading',
    name: 'Heading',
    description: 'Large editorial text layer.',
    category: 'text',
    layers: [
      {
        id: 'preset-heading',
        type: 'text',
        name: 'Heading',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 160, y: 152, width: 860, height: 130 },
        style: {
          color: '#ffffff',
          fontSize: 88,
          fontWeight: 800,
          lineHeight: 1.02,
        },
        props: { text: 'Heading' },
      },
    ],
  },
  {
    id: 'text-subtitle',
    name: 'Subtitle',
    description: 'Compact supporting copy.',
    category: 'text',
    layers: [
      {
        id: 'preset-subtitle',
        type: 'text',
        name: 'Subtitle',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 164, y: 300, width: 760, height: 80 },
        style: {
          color: '#dbeafe',
          fontSize: 38,
          fontWeight: 500,
          lineHeight: 1.16,
        },
        props: { text: 'Subtitle text' },
      },
    ],
  },
  {
    id: 'text-kicker',
    name: 'Kicker',
    description: 'Small uppercase label.',
    category: 'text',
    layers: [
      {
        id: 'preset-kicker',
        type: 'text',
        name: 'Kicker',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 160, y: 110, width: 460, height: 44 },
        style: {
          color: '#93c5fd',
          fontSize: 28,
          fontWeight: 700,
          lineHeight: 1,
          letterSpacing: 2,
        },
        props: { text: 'SECTION' },
      },
    ],
  },
  {
    id: 'text-number',
    name: 'Number',
    description: 'Large metric number.',
    category: 'text',
    layers: [
      {
        id: 'preset-number',
        type: 'text',
        name: 'Number',
        start: 0,
        duration: 3200,
        zIndex: 3,
        layout: { x: 152, y: 178, width: 560, height: 160 },
        style: {
          color: '#ffffff',
          fontSize: 118,
          fontWeight: 800,
          lineHeight: 0.96,
        },
        props: { text: '+42%' },
      },
    ],
  },
  {
    id: 'shape-card',
    name: 'Card',
    description: 'Rounded surface block.',
    category: 'shape',
    layers: [
      {
        id: 'preset-card',
        type: 'shape',
        name: 'Card',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 120, y: 128, width: 780, height: 420 },
        style: { background: '#ffffff', borderRadius: 36 },
        props: { kind: 'rectangle' },
      },
    ],
  },
  {
    id: 'shape-pill',
    name: 'Pill',
    description: 'Rounded label shape.',
    category: 'shape',
    layers: [
      {
        id: 'preset-pill',
        type: 'shape',
        name: 'Pill',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 150, y: 150, width: 340, height: 86 },
        style: { background: '#2563eb', borderRadius: 999 },
        props: { kind: 'rectangle' },
      },
    ],
  },
  {
    id: 'shape-circle',
    name: 'Circle',
    description: 'Circular accent element.',
    category: 'shape',
    layers: [
      {
        id: 'preset-circle',
        type: 'shape',
        name: 'Circle',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 240, y: 190, width: 260, height: 260 },
        style: { background: '#22d3ee', borderRadius: 999 },
        props: { kind: 'ellipse' },
      },
    ],
  },
  {
    id: 'shape-line',
    name: 'Line',
    description: 'Thin divider or underline.',
    category: 'shape',
    layers: [
      {
        id: 'preset-line',
        type: 'shape',
        name: 'Line',
        start: 0,
        duration: 3200,
        zIndex: 1,
        layout: { x: 160, y: 380, width: 520, height: 12 },
        style: { background: '#60a5fa', borderRadius: 999 },
        props: { kind: 'rectangle' },
      },
    ],
  },
  {
    id: 'title-reveal',
    name: 'Title reveal',
    description: 'Large title with an animated accent bar.',
    category: 'scene',
    layers: [
      {
        id: 'preset-title',
        type: 'text',
        name: 'Title',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 140, y: 180, width: 980, height: 180 },
        style: {
          color: '#ffffff',
          fontSize: 86,
          fontWeight: 700,
          lineHeight: 1.05,
        },
        props: { text: 'New scene' },
        transitions: {
          in: {
            type: 'slide',
            duration: 600,
            easing: 'easeOutCubic',
            props: { direction: 'left', distance: 140 },
          },
          out: {
            type: 'fade',
            duration: 500,
            easing: 'easeInOutCubic',
          },
        },
        animations: [
          {
            property: 'opacity',
            keyframes: [
              { time: 0, value: 0 },
              { time: 500, value: 1, easing: 'easeOutCubic' },
            ],
          },
          {
            property: 'y',
            keyframes: [
              { time: 0, value: 218 },
              { time: 500, value: 180, easing: 'easeOutCubic' },
            ],
          },
        ],
      },
      {
        id: 'preset-accent',
        type: 'shape',
        name: 'Accent',
        start: 120,
        duration: 3200,
        zIndex: 1,
        layout: { x: 140, y: 380, width: 520, height: 16 },
        style: { background: '#22d3ee', borderRadius: 999 },
        props: { kind: 'rectangle' },
        transitions: {
          in: {
            type: 'wipe',
            duration: 650,
            easing: 'easeOutCubic',
            props: { direction: 'left' },
          },
        },
        animations: [
          {
            property: 'width',
            keyframes: [
              { time: 0, value: 0 },
              { time: 520, value: 520, easing: 'easeOutCubic' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'lower-third-name',
    name: 'Name lower third',
    description: 'Name and role caption bar.',
    category: 'lower-third',
    layers: [
      {
        id: 'preset-lt-bg',
        type: 'shape',
        name: 'Lower third panel',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 120, y: 760, width: 860, height: 150 },
        style: { background: '#ffffff', borderRadius: 28 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-lt-name',
        type: 'text',
        name: 'Name',
        start: 0,
        duration: 3600,
        zIndex: 3,
        layout: { x: 170, y: 792, width: 620, height: 58 },
        style: { color: '#0f172a', fontSize: 44, fontWeight: 800, lineHeight: 1 },
        props: { text: 'Alex Morgan' },
      },
      {
        id: 'preset-lt-role',
        type: 'text',
        name: 'Role',
        start: 0,
        duration: 3600,
        zIndex: 3,
        layout: { x: 172, y: 852, width: 640, height: 38 },
        style: { color: '#475569', fontSize: 26, fontWeight: 500, lineHeight: 1 },
        props: { text: 'VP Revenue Operations' },
      },
    ],
  },
  {
    id: 'metric-card',
    name: 'Metric card',
    description: 'Card with metric and label.',
    category: 'metric',
    layers: [
      {
        id: 'preset-metric-bg',
        type: 'shape',
        name: 'Metric panel',
        start: 0,
        duration: 3600,
        zIndex: 1,
        layout: { x: 132, y: 150, width: 620, height: 360 },
        style: { background: '#1e293b', borderRadius: 34 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-metric-value',
        type: 'text',
        name: 'Metric value',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 188, y: 236, width: 440, height: 128 },
        style: { color: '#ffffff', fontSize: 104, fontWeight: 800, lineHeight: 0.95 },
        props: { text: '+42%' },
      },
      {
        id: 'preset-metric-label',
        type: 'text',
        name: 'Metric label',
        start: 0,
        duration: 3600,
        zIndex: 2,
        layout: { x: 194, y: 380, width: 420, height: 42 },
        style: { color: '#bfdbfe', fontSize: 30, fontWeight: 500, lineHeight: 1 },
        props: { text: 'Pipeline growth' },
      },
    ],
  },
  {
    id: 'background-blueprint',
    name: 'Blueprint background',
    description: 'Full frame technical backdrop.',
    category: 'background',
    layers: [
      {
        id: 'preset-bg-blue',
        type: 'shape',
        name: 'Blueprint background',
        start: 0,
        duration: 5000,
        zIndex: -10,
        layout: { x: 0, y: 0, width: 1920, height: 1080 },
        style: { background: '#0f172a', borderRadius: 0 },
        props: { kind: 'rectangle' },
      },
      {
        id: 'preset-bg-panel',
        type: 'shape',
        name: 'Soft panel',
        start: 0,
        duration: 5000,
        zIndex: -9,
        layout: { x: 1180, y: 120, width: 520, height: 780 },
        style: { background: '#1d4ed8', borderRadius: 46 },
        props: { kind: 'rectangle' },
      },
    ],
  },
];
